import os
import sys

sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from .nodes.json_corrector_node import NODE_CLASS_MAPPINGS as CORRECTOR_NODE_MAPPINGS
from .nodes.json_corrector_node import NODE_DISPLAY_NAME_MAPPINGS as CORRECTOR_DISPLAY_MAPPINGS

from .nodes.json_extractor_node import NODE_CLASS_MAPPINGS as EXTRACTOR_NODE_MAPPINGS
from .nodes.json_extractor_node import NODE_DISPLAY_NAME_MAPPINGS as EXTRACTOR_DISPLAY_MAPPINGS

# 合并所有节点映射
NODE_CLASS_MAPPINGS = {}
NODE_CLASS_MAPPINGS.update(CORRECTOR_NODE_MAPPINGS)
NODE_CLASS_MAPPINGS.update(EXTRACTOR_NODE_MAPPINGS)

NODE_DISPLAY_NAME_MAPPINGS = {}
NODE_DISPLAY_NAME_MAPPINGS.update(CORRECTOR_DISPLAY_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(EXTRACTOR_DISPLAY_MAPPINGS)

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']
